import { Team, Question, GameSettings, QuestionSet } from '../types';

export const DEFAULT_TEAMS: Team[] = [
  {
    id: 'team-orange',
    name: 'Đội Cam Rực Lửa',
    color: '#F26F21', // FPT Orange
    bgGradient: 'from-orange-500 to-amber-600',
    textColor: 'text-orange-500',
    borderColor: 'border-orange-500',
    icon: '🦁',
    score: 0,
  },
  {
    id: 'team-blue',
    name: 'Đội Xanh Đại Dương',
    color: '#2563EB',
    bgGradient: 'from-blue-600 to-cyan-600',
    textColor: 'text-blue-500',
    borderColor: 'border-blue-500',
    icon: '🚀',
    score: 0,
  },
  {
    id: 'team-red',
    name: 'Đội Đỏ Chiến Thắng',
    color: '#DC2626',
    bgGradient: 'from-red-600 to-rose-600',
    textColor: 'text-red-500',
    borderColor: 'border-red-500',
    icon: '⚡',
    score: 0,
  },
  {
    id: 'team-green',
    name: 'Đội Xanh Lá Thông Thái',
    color: '#16A34A',
    bgGradient: 'from-emerald-600 to-teal-600',
    textColor: 'text-emerald-500',
    borderColor: 'border-emerald-500',
    icon: '🐉',
    score: 0,
  },
  {
    id: 'team-purple',
    name: 'Đội Tím Huyền Bí',
    color: '#9333EA',
    bgGradient: 'from-purple-600 to-indigo-600',
    textColor: 'text-purple-500',
    borderColor: 'border-purple-500',
    icon: '🌟',
    score: 0,
  },
  {
    id: 'team-yellow',
    name: 'Đội Vàng Ánh Dương',
    color: '#EAB308',
    bgGradient: 'from-yellow-500 to-amber-500',
    textColor: 'text-yellow-500',
    borderColor: 'border-yellow-500',
    icon: '🦅',
    score: 0,
  },
];

export const DEFAULT_QUESTIONS: Question[] = [
  // TOÁN HỌC
  {
    id: 'q-math-1',
    subject: 'Toán Học',
    gradeLevel: 'Tiểu học',
    type: 'MULTIPLE_CHOICE',
    question: 'Số chẵn lớn nhất có 2 chữ số khác nhau là số nào?',
    options: ['99', '98', '96', '90'],
    correctAnswer: 1, // 98
    explanation: 'Số chẵn lớn nhất có 2 chữ số khác nhau là 98 (99 là số lẻ).',
    points: 20,
  },
  {
    id: 'q-math-2',
    subject: 'Toán Học',
    gradeLevel: 'Tiểu học / THCS',
    type: 'MULTIPLE_CHOICE',
    question: 'Một hình vuông có chu vi là 36cm. Diện tích của hình vuông đó là bao nhiêu?',
    options: ['81 cm²', '36 cm²', '72 cm²', '64 cm²'],
    correctAnswer: 0, // 81 cm²
    explanation: 'Cạnh hình vuông = 36 : 4 = 9 cm. Diện tích = 9 × 9 = 81 cm².',
    points: 20,
  },
  {
    id: 'q-math-3',
    subject: 'Toán Học',
    gradeLevel: 'THCS',
    type: 'SHORT_ANSWER',
    question: 'Tìm x biết: 3x + 15 = 45. Giá trị của x là bao nhiêu?',
    correctAnswer: '10',
    explanation: '3x = 45 - 15 = 30 => x = 30 / 3 = 10.',
    points: 30,
  },

  // TIẾNG VIỆT & NGỮ VĂN
  {
    id: 'q-viet-1',
    subject: 'Tiếng Việt',
    gradeLevel: 'Tiểu học',
    type: 'MULTIPLE_CHOICE',
    question: 'Thành ngữ nào sau đây mang ý nghĩa chỉ tinh thần đoàn kết, giúp đỡ lẫn nhau?',
    options: ['Lá lành đùm lá rách', 'Có công mài sắt có ngày nên kim', 'Học thầy không tày học bạn', 'Đi một ngày đàng học một sàng khôn'],
    correctAnswer: 0,
    explanation: '"Lá lành đùm lá rách" thể hiện tinh thần tương thân tương ái, cưu mang giúp đỡ đồng bào.',
    points: 20,
  },
  {
    id: 'q-viet-2',
    subject: 'Tiếng Việt',
    gradeLevel: 'Tiểu học',
    type: 'SHORT_ANSWER',
    question: 'Từ trái nghĩa với từ "Dũng cảm" là gì?',
    correctAnswer: 'Nhút nhát',
    explanation: 'Các từ trái nghĩa: Nhút nhát, hèn nhát, sợ sệt.',
    points: 20,
  },
  {
    id: 'q-viet-3',
    subject: 'Ngữ Văn',
    gradeLevel: 'THCS',
    type: 'MULTIPLE_CHOICE',
    question: 'Tác giả của bài thơ "Lượm" - chú bé liên lạc dũng cảm là ai?',
    options: ['Tố Hữu', 'Trần Đăng Khoa', 'Huy Cận', 'Xuân Quỳnh'],
    correctAnswer: 0,
    explanation: 'Bài thơ "Lượm" được nhà thơ Tố Hữu sáng tác năm 1949 trong thời kỳ kháng chiến chống Pháp.',
    points: 20,
  },

  // TIẾNG ANH
  {
    id: 'q-eng-1',
    subject: 'Tiếng Anh',
    gradeLevel: 'Chung',
    type: 'MULTIPLE_CHOICE',
    question: 'What is the opposite of the word "HOT"?',
    options: ['Warm', 'Cold', 'Sunny', 'Dry'],
    correctAnswer: 1, // Cold
    explanation: 'Opposite of Hot is Cold (Nóng trái nghĩa với Lạnh).',
    points: 10,
  },
  {
    id: 'q-eng-2',
    subject: 'Tiếng Anh',
    gradeLevel: 'Chung',
    type: 'MULTIPLE_CHOICE',
    question: 'How many days are there in a Leap Year (Năm nhuận)?',
    options: ['364', '365', '366', '367'],
    correctAnswer: 2, // 366
    explanation: 'A leap year has 366 days because February has 29 days.',
    points: 20,
  },
  {
    id: 'q-eng-3',
    subject: 'Tiếng Anh',
    gradeLevel: 'Chung',
    type: 'SHORT_ANSWER',
    question: 'Translate the word "Hạnh phúc" into English:',
    correctAnswer: 'Happy',
    explanation: 'Happy / Happiness đều chính xác.',
    points: 20,
  },

  // KHOA HỌC & TỰ NHIÊN
  {
    id: 'q-sci-1',
    subject: 'Khoa Học',
    gradeLevel: 'Tiểu học / THCS',
    type: 'MULTIPLE_CHOICE',
    question: 'Hành tinh nào gần Mặt Trời nhất trong Hệ Mặt Trời?',
    options: ['Sao Kim (Venus)', 'Sao Thủy (Mercury)', 'Trái Đất (Earth)', 'Sao Hỏa (Mars)'],
    correctAnswer: 1, // Sao Thủy
    explanation: 'Sao Thủy (Mercury) là hành tinh nằm gần Mặt Trời nhất.',
    points: 20,
  },
  {
    id: 'q-sci-2',
    subject: 'Khoa Học',
    gradeLevel: 'Tiểu học',
    type: 'MULTIPLE_CHOICE',
    question: 'Cây xanh quang hợp hút khí gì và nhả ra khí gì vào ban ngày?',
    options: [
      'Hút Oxy, nhả Carbonic',
      'Hút Carbonic (CO₂), nhả Oxy (O₂)',
      'Hút Nitơ, nhả Oxy',
      'Hút Hơi nước, nhả CO₂'
    ],
    correctAnswer: 1,
    explanation: 'Quá trình quang hợp của cây xanh hấp thụ khí CO₂ và giải phóng khí O₂.',
    points: 20,
  },
  {
    id: 'q-sci-3',
    subject: 'Khoa Học',
    gradeLevel: 'THCS',
    type: 'SHORT_ANSWER',
    question: 'Nước sôi ở bao nhiêu độ C ở áp suất tiêu chuẩn (1 atm)?',
    correctAnswer: '100',
    explanation: 'Nước tinh khiết sôi ở 100°C (hoặc 212°F).',
    points: 10,
  },

  // LỊCH SỬ & ĐỊA LÝ
  {
    id: 'q-his-1',
    subject: 'Lịch Sử - Địa Lý',
    gradeLevel: 'Chung',
    type: 'MULTIPLE_CHOICE',
    question: 'Đỉnh núi nào được mệnh danh là "Nóc nhà Đông Dương"?',
    options: ['Fansipan (Phan Xi Păng)', 'Núi Mẫu Sơn', 'Núi Bà Đen', 'Núi Langbiang'],
    correctAnswer: 0,
    explanation: 'Fansipan cao 3.143m thuộc dãy Hoàng Liên Sơn là đỉnh núi cao nhất 3 nước Đông Dương.',
    points: 20,
  },
  {
    id: 'q-his-2',
    subject: 'Lịch Sử - Địa Lý',
    gradeLevel: 'Chung',
    type: 'MULTIPLE_CHOICE',
    question: 'Chiến thắng Điện Biên Phủ "lừng lẫy năm châu, chấn động địa cầu" diễn ra vào năm nào?',
    options: ['1945', '1954', '1975', '1986'],
    correctAnswer: 1, // 1954
    explanation: 'Chiến dịch Điện Biên Phủ toàn thắng vào ngày 7 tháng 5 năm 1954.',
    points: 20,
  },
  {
    id: 'q-his-3',
    subject: 'Lịch Sử - Địa Lý',
    gradeLevel: 'Chung',
    type: 'SHORT_ANSWER',
    question: 'Việt Nam có đường bờ biển dài khoảng bao nhiêu km? (Gần đúng)',
    correctAnswer: '3260',
    explanation: 'Bờ biển Việt Nam dài khoảng 3.260 km từ Móng Cái đến Hà Tiên.',
    points: 30,
  },

  // TIN HỌC & CÔNG NGHỆ
  {
    id: 'q-it-1',
    subject: 'Tin Học',
    gradeLevel: 'Chung',
    type: 'MULTIPLE_CHOICE',
    question: 'Phím tắt nào trên bàn phím dùng để SAO CHÉP (Copy) văn bản hoặc hình ảnh?',
    options: ['Ctrl + V', 'Ctrl + C', 'Ctrl + X', 'Ctrl + Z'],
    correctAnswer: 1,
    explanation: 'Ctrl + C dùng để Copy, Ctrl + V để Paste, Ctrl + X để Cut, Ctrl + Z để Undo.',
    points: 10,
  },
  {
    id: 'q-it-2',
    subject: 'Tin Học',
    gradeLevel: 'Chung',
    type: 'MULTIPLE_CHOICE',
    question: 'AI là viết tắt của cụm từ tiếng Anh nào?',
    options: ['Automatic Internet', 'Artificial Intelligence', 'Apple Intelligence', 'Auto Information'],
    correctAnswer: 1,
    explanation: 'Artificial Intelligence nghĩa là Trí tuệ Nhân tạo.',
    points: 10,
  },

  // ĐỐ VUI TRÍ TUỆ
  {
    id: 'q-fun-1',
    subject: 'Đố Vui',
    gradeLevel: 'Mọi lứa tuổi',
    type: 'MULTIPLE_CHOICE',
    question: 'Con gì đầu dê mình ốc, đi đến đâu dãi nhớt đến đó?',
    options: ['Con ốc sên', 'Con rùa', 'Con cua', 'Con trăn'],
    correctAnswer: 0,
    explanation: 'Con ốc sên có 2 cái râu như sừng dê và mang mai ốc trên lưng!',
    points: 20,
  },
  {
    id: 'q-fun-2',
    subject: 'Đố Vui',
    gradeLevel: 'Mọi lứa tuổi',
    type: 'SHORT_ANSWER',
    question: 'Cái gì chặt không đứt, bứt không rời, phơi không khô, đốt không cháy?',
    correctAnswer: 'Nước',
    explanation: 'Đáp án là dòng nước!',
    points: 20,
  },
];

export const DEFAULT_QUESTION_SETS: QuestionSet[] = [
  {
    id: 'set-default-all',
    name: 'Bộ Tổng Hợp Khởi Động (Đa Môn)',
    description: 'Bộ câu hỏi phong phú đa dạng bao gồm Toán, Tiếng Anh, Khoa Học, Văn Học, Lịch Sử và Đố Vui.',
    subject: 'Tổng Hợp',
    createdAt: '2026-09-01',
    isDefault: true,
    questions: DEFAULT_QUESTIONS,
  },
  {
    id: 'set-math-logic',
    name: 'Bộ Câu Hỏi: Toán Học & Tư Duy Logic',
    description: 'Rèn luyện phản xạ tính nhẩm, hình học, số học và giải toán nhanh cho học sinh.',
    subject: 'Toán Học',
    createdAt: '2026-09-01',
    isDefault: true,
    questions: DEFAULT_QUESTIONS.filter((q) => q.subject === 'Toán Học'),
  },
  {
    id: 'set-science-english',
    name: 'Bộ Câu Hỏi: Tiếng Anh & Khoa Học',
    description: 'Từ vựng tiếng Anh giao tiếp, hiện tượng thiên nhiên và kiến thức khoa học đời sống.',
    subject: 'Tiếng Anh - Khoa Học',
    createdAt: '2026-09-01',
    isDefault: true,
    questions: DEFAULT_QUESTIONS.filter((q) => q.subject === 'Tiếng Anh' || q.subject === 'Khoa Học'),
  },
  {
    id: 'set-history-geo-vn',
    name: 'Bộ Câu Hỏi: Lịch Sử & Địa Lý Việt Nam',
    description: 'Tìm hiểu danh lam thắng cảnh, thủ đô, anh hùng dân tộc và mốc son lịch sử Việt Nam.',
    subject: 'Lịch Sử - Địa Lý',
    createdAt: '2026-09-01',
    isDefault: true,
    questions: DEFAULT_QUESTIONS.filter((q) => q.subject === 'Lịch Sử - Địa Lý' || q.subject === 'Ngữ Văn' || q.subject === 'Tiếng Việt'),
  },
  {
    id: 'set-fun-trivia',
    name: 'Bộ Câu Hỏi: Đố Vui & Trí Não Nhanh Nhạy',
    description: 'Những câu đố mẹo dân gian và kiến thức công nghệ vui nhộn khuấy động không khí lớp học.',
    subject: 'Đố Vui',
    createdAt: '2026-09-01',
    isDefault: true,
    questions: DEFAULT_QUESTIONS.filter((q) => q.subject === 'Đố Vui' || q.subject === 'Tin Học'),
  },
];

export const DEFAULT_SETTINGS: GameSettings = {
  moveDurationSec: 6,
  scanDurationSec: 3,
  pickDurationSec: 3,
  soundEnabled: true,
  musicEnabled: true,
  musicTrack: 'funk',
  musicVolume: 80,
  isDemoMode: false,
  schoolName: 'Trường Tiểu học & THCS',
  classroomName: 'Lớp 5A / Lớp 6A1',
  teacherName: 'Thầy/Cô Giáo',
  randomQuestionOrder: true,
  cameraFacingMode: 'user',
  motionSensitivity: 5,
};
